const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"safety":async(p,click,select,check)=>{A.equal(await p.locator('#rhythm-volume-caution').innerText(),'Start with your volume low.');A(await p.locator('#rhythm-volume-caution').evaluate(e=>e.checkVisibility()));A.equal(await p.locator('#rhythm-sound').isChecked(),false);A.equal(await p.locator('#rhythm-play-drawer>summary').innerText(),'Playing a few measures');await select('rhythm-measures','2');A.equal(await p.locator('#rhythm-play').innerText(),'Play two measures');A(await p.locator('#rhythm-volume-caution').evaluate(e=>e.checkVisibility()));},
"rollthree":async(p,click,select,check)=>{await check('rhythm-a-note-1',false);await select('rhythm-offset','1');const old=await p.locator('#rhythm-b-slots').innerText();await click('rhythm-roll-a-forward');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 1, 5.');A.equal(await p.locator('#rhythm-b-slots').innerText(),old);await click('rhythm-undo');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 1, 9.');await click('rhythm-roll-a-back');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 5, 9.');A.equal(await p.evaluate(()=>__audio.starts),0);},
"meetingsonly":async(p,click,select,check)=>{await select('rhythm-offset','1');await click('rhythm-keep-meetings');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 5.');A.equal(await p.locator('#rhythm-b-slots').innerText(),'Four plays slots: 5.');A(await p.locator('#rhythm-keep-meetings').isDisabled());await click('rhythm-undo');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 1, 5, 9.');A.equal(await p.locator('#rhythm-b-slots').innerText(),'Four plays slots: 2, 5, 8, 11.');A.equal(await p.evaluate(()=>__audio.starts),0);}
};
const messages={"safety":"finite rhythm playback keeps its sound-off default and visible volume caution","rollthree": "rolling the three-note mask changes enabled beats in one reversible press", "meetingsonly": "keeping only together notes removes solos atomically and Undo restores them"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
