const cases={
"finitecycles":async(p,click,select,check)=>{await select('rhythm-measures','2');await check('rhythm-sound',true);await click('rhythm-play');A.equal(await p.evaluate(()=>__audio.buffers.at(-1).length),576000);A.equal(await p.evaluate(()=>__audio.starts),1);await click('rhythm-pause');await select('rhythm-measures','4');A.ok(await p.locator('#rhythm-resume').isDisabled());await click('rhythm-play');A.equal(await p.evaluate(()=>__audio.buffers.at(-1).length),1152000);await click('rhythm-stop');},
"voices":async(p,click,select,check)=>{await select('rhythm-voices','swapped');await select('rhythm-hear-track','a');await check('rhythm-sound',true);await click('rhythm-play');const r=await p.evaluate(()=>__audio.buffers.at(-1).getChannelData(0)[240]);A.ok(Math.abs(r-.07*Math.sin(2*Math.PI*330*.005))<1e-7);A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 1, 5, 9.');await click('rhythm-stop');},
"invertmask":async(p,click,select,check)=>{await check('rhythm-a-note-1',false);await click('rhythm-invert-a');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 5.');A.equal(await p.locator('#rhythm-b-slots').innerText(),'Four plays slots: 1, 4, 7, 10.');await click('rhythm-undo');A.equal(await p.locator('#rhythm-a-slots').innerText(),'Three plays slots: 1, 9.');A.equal(await p.evaluate(()=>__audio.starts),0);}
};
const messages={"finitecycles": "two and four measures remain finite and keep a single sound source", "voices": "swapping rhythm voices changes samples but not note slots or masks", "invertmask": "turning one rhythm into its missing notes is one reversible pattern change"};
const A=require('node:assert/strict'),{chromium}=require('playwright-core');const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={buffers:[],starts:0,stops:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(ch,n,r){const a=new Float32Array(n);const b={length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)};__audio.buffers.push(b);return b}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){__audio.stops++},loop:false}}}window.AudioContext=C;window.webkitAudioContext=C};
(async()=>{A.ok(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(String(e)));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(100);const reveal=async l=>{const ds=await l.evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a});for(const d of ds){const s=p.locator('#'+d+'>summary');await s.scrollIntoViewIfNeeded();await s.click()}};const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A.ok(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await l.click();await p.waitForTimeout(60)};const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(60)};const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(60)};await cases[mode](p,click,select,check);A.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));A.deepEqual(errors,[]);await p.screenshot({path:`/tmp/pm-${mode}-${width}.png`,fullPage:true});await p.close()}await b.close();console.log(messages[mode])})().catch(e=>{console.error(e);process.exit(1)});
