const A=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright-core');
const spec=JSON.parse(fs.readFileSync(__dirname+'/planner-oct12.json','utf8')),mode=process.argv[2],url=process.argv[3];
async function hit(p,l){await l.scrollIntoViewIfNeeded();A(await l.isEnabled());A(await l.evaluate(e=>{let r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await l.click();await p.waitForTimeout(90)}
async function reveal(p,l){let ids=await l.evaluate(e=>{let a=[];for(let n=e.tagName==='SUMMARY'?e.parentElement.parentElement:e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(let id of ids){A(id);await hit(p,p.locator('#'+id+'>summary'))}}
async function click(p,s){let l=p.locator(s);await reveal(p,l);await hit(p,l)}
async function select(p,s,v){let l=p.locator(s);await reveal(p,l);await l.selectOption(v);await p.waitForTimeout(90)}
async function input(p,s,v){let l=p.locator(s);await reveal(p,l);await l.focus();await p.keyboard.press('Home');let min=Number(await l.getAttribute('min')),step=Number(await l.getAttribute('step'));for(let i=0;i<Math.round((v-min)/step);i++)await p.keyboard.press('ArrowRight');await p.waitForTimeout(90);A.equal(Number(await l.inputValue()),v)}
async function pattern(p){return p.evaluate(()=>({a:[0,1,2].map(i=>document.querySelector('#rhythm-a-note-'+i).checked),b:[0,1,2,3].map(i=>document.querySelector('#rhythm-b-note-'+i).checked),offset:Number(document.querySelector('#rhythm-offset').value)}))}
async function points(p){return p.locator('#mask [data-hole-index]').evaluateAll(es=>es.map(e=>({x:Number(e.dataset.x),y:Number(e.dataset.y)})))}
async function controls(p){return p.evaluate(()=>[...document.querySelectorAll('input[id],select[id]')].map(e=>[e.id,e.value,e.checked]))}
async function run(p,c){
 if(c.kind==='sun'){await click(p,'#preset-two-note-braid');const old=await p.evaluate(()=>__sunflower.heldInDrawnOrder());let keep=p.locator('#remember-drawing');if(await keep.count())await click(p,'#remember-drawing');const memory=await p.evaluate(()=>__sunflower.rememberedDrawing());for(let [id,label,ids]of c.rows){const before=await p.evaluate(()=>__sunflower.heldInDrawnOrder()),n=await p.evaluate(()=>__sunflower.undoDepth());A.equal(await p.locator('#'+id).textContent(),label);await click(p,'#'+id);A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),ids);A.equal(await p.evaluate(()=>__sunflower.undoDepth()),n+1);await click(p,'#'+id);A.equal(await p.evaluate(()=>__sunflower.undoDepth()),n+1);A.deepEqual(await p.evaluate(()=>__sunflower.rememberedDrawing()),memory);await click(p,'#undo-drawing');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),before)}}
 if(c.kind==='holes'){for(let [id,label,ps]of c.rows){const before=await points(p);A.equal(await p.locator('[data-preset='+id+']').textContent(),label);await click(p,'[data-preset='+id+']');A.deepEqual(await points(p),ps);await click(p,'#mask-undo');A.deepEqual(await points(p),before);await click(p,'#mask-redo');A.deepEqual(await points(p),ps)}}
 if(c.kind==='values'){let d=p.locator('#'+c.door);A.equal(await d.evaluate(e=>e.open),false);A.equal(await d.locator(':scope>summary').textContent(),c.summary);const before=await controls(p);await click(p,'#'+c.door+'>summary');A.deepEqual(await controls(p),before);const old=await Promise.all(c.fields.map(id=>p.locator('#'+id).inputValue()));await click(p,'#'+c.keep);for(let [id,label,values]of c.rows){await select(p,'#'+c.select,id);A.equal(await p.locator('#'+c.select+' option:checked').textContent(),label);await click(p,'#'+c.apply);A.deepEqual(await Promise.all(c.fields.map(id=>p.locator('#'+id).inputValue())),values);A(await p.locator('#'+c.apply).isDisabled());if(spec.slug==='fading-light'){let [r,rb,k,a,pat,count,rate,unit,n]=values.map((v,i)=>i===4||i===5||i===7?v:Number(v));let retention=unit==='second'?r**(30/rate):r,val=a;for(let j=1;j<=n;j++)val=Math.min(1,retention*val+(j%k===0&&(count==='all'||j/k<=Number(count))?a:0));A(Math.abs(Number(await p.locator('#train-cursor').getAttribute('cy'))-(144-128*val))<1e-9);A.equal((await p.locator('#chart-seconds text').allTextContents())[2],(120/rate).toFixed(2)+' s')}}await click(p,'#'+c.return);A.deepEqual(await Promise.all(c.fields.map(id=>p.locator('#'+id).inputValue())),old)}
 if(c.kind==='rhythm'){const d=p.locator('#'+c.door);A.equal(await d.evaluate(e=>e.open),false);A.equal(await d.locator(':scope>summary').textContent(),c.summary);const choices=await controls(p);await click(p,'#'+c.door+'>summary');A.deepEqual(await controls(p),choices);for(let [id,label,pat]of c.rows){const old=await pattern(p);await select(p,'#'+c.select,id);A.equal(await p.locator('#'+c.select+' option:checked').textContent(),label);await click(p,'#'+c.apply);A.deepEqual(await pattern(p),pat);A(await p.locator('#'+c.apply).isDisabled());await click(p,'#rhythm-undo');A.deepEqual(await pattern(p),old)}}
 if(c.kind==='flock'){const prior=await p.evaluate(()=>__flock.state());for(let [id,label,radial,tangent]of c.rows){A.equal(await p.locator('#sky-'+id).textContent(),label);await click(p,'#sky-'+id);const s=await p.evaluate(()=>__flock.state());const expected=await p.evaluate(([radial,tangent])=>Array.from({length:80},(_,i)=>{let t=2*Math.PI*i/80;return{x:500+180*Math.cos(t),y:300+180*Math.sin(t),vx:radial*Math.cos(t)-tangent*Math.sin(t),vy:radial*Math.sin(t)+tangent*Math.cos(t)}}),[radial,tangent]);A.deepEqual(s.birds,expected);A.deepEqual(s.weights,prior.weights);A.equal(s.pace,prior.pace);A.equal(s.paused,true);A.equal(s.undoBeats,0)}}
 if(c.kind==='opposite'){await input(p,'#probe-u',1.25);await input(p,'#probe-v',-.75);const old=await points(p),undo=await p.locator('#mask-undo').isDisabled(),bright=await p.locator('#brightness').textContent();await click(p,'#probe-opposite');A.equal(await p.locator('#probe-u').inputValue(),'-1.25');A.equal(await p.locator('#probe-v').inputValue(),'0.75');A.equal(await p.locator('#brightness').textContent(),bright);A.deepEqual(await points(p),old);A.equal(await p.locator('#mask-undo').isDisabled(),undo);await click(p,'#probe-opposite');A.equal(await p.locator('#probe-u').inputValue(),'1.25');A.equal(await p.locator('#probe-v').inputValue(),'-.75'.replace('-.','-0.'));await input(p,'#probe-u',0);await input(p,'#probe-v',0);A(await p.locator('#probe-opposite').isDisabled())}
 if(c.kind==='reverse'){await click(p,'#rhythm-a-note-1');await click(p,'#rhythm-b-note-1');await select(p,'#rhythm-offset','1');const old=await pattern(p);await click(p,'#rhythm-reverse-measure');A.deepEqual(await pattern(p),{a:[true,true,false],b:[true,true,true,false],offset:11});await click(p,'#rhythm-reverse-measure');A.deepEqual(await pattern(p),old);await click(p,'#rhythm-undo');A.deepEqual(await pattern(p),{a:[true,true,false],b:[true,true,true,false],offset:11});await click(p,'#rhythm-reset-pattern');A(await p.locator('#rhythm-reverse-measure').isDisabled())}
}
(async()=>{A(mode==='baseline'||spec.cases[mode]);let b=await chromium.launch({args:['--no-sandbox']});try{for(let width of[390,1280]){let p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.__contexts=0;let C=window.AudioContext;if(C)window.AudioContext=class extends C{constructor(...a){super(...a);window.__contexts++}}});A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(150);if(mode!=='baseline')await run(p,spec.cases[mode]);else{A(await p.locator('h1').count());A.equal(await p.evaluate(()=>[...document.querySelectorAll('[id]')].map(e=>e.id).filter((id,i,a)=>a.indexOf(id)!==i).length),0)}A.equal(await p.evaluate(()=>__contexts),0);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/oct12-${spec.slug}-${mode}-${width}.png`,fullPage:true});await p.close()}console.log(mode==='baseline'?spec.slug+' original page opens silently':spec.cases[mode].message)}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
